In [ ]:
import pandas as pd

In [ ]:
# Vamos agora criar uma série e armazenar notas de alunos da Let's Code

# Cria Serie com valores de notas para cada aluno
notas = pd.Series([10, 8, 6.5, 9, 7.5, 8.5, 9, 9, 4, 8.5, 7.5,
                   8, 10, 10, 4.5, 4.5, 9, 8, 8, 9, 9, 9, 6.5,
                   5, 6, 4.5, 9, 10, 1, 0,5, 7, 9, 6.5, 5, 8])

# Mostra o resultado da Serie criada
notas

0     10.0
1      8.0
2      6.5
3      9.0
4      7.5
5      8.5
6      9.0
7      9.0
8      4.0
9      8.5
10     7.5
11     8.0
12    10.0
13    10.0
14     4.5
15     4.5
16     9.0
17     8.0
18     8.0
19     9.0
20     9.0
21     9.0
22     6.5
23     5.0
24     6.0
25     4.5
26     9.0
27    10.0
28     1.0
29     0.0
30     5.0
31     7.0
32     9.0
33     6.5
34     5.0
35     8.0
dtype: float64

In [ ]:
notas.sort_values()

29     0.0
28     1.0
8      4.0
15     4.5
14     4.5
25     4.5
23     5.0
34     5.0
30     5.0
24     6.0
22     6.5
2      6.5
33     6.5
31     7.0
4      7.5
10     7.5
18     8.0
17     8.0
35     8.0
1      8.0
11     8.0
9      8.5
5      8.5
19     9.0
20     9.0
21     9.0
32     9.0
26     9.0
16     9.0
7      9.0
6      9.0
3      9.0
27    10.0
13    10.0
12    10.0
0     10.0
dtype: float64

2) Considere uma série de notas de alunos:

notas = pd.Série([10, 8, 6,5, 9, 7,5, 8,5, 9, 9, 4, 8,5, 7,5, 8, 10, 10, 4,5, 4,5, 9, 8, 8, 9, 9, 9, 6,5, 5, 6, 4,5, 9, 10, 1, 0,5, 7, 9, 6,5, 5, 8])

Determinar:

a) A nota média

b) O/ padrão

c) Uma moda

d) Uma mediana

In [ ]:
notas = pd.Series([10, 8, 6.5, 9, 7.5, 8.5, 9, 9, 4, 8.5, 7.5,
                8, 10, 10, 4.5, 4.5, 9, 8, 8, 9, 9, 9, 6.5,
                5, 6, 4.5, 9, 10, 1, 0,5, 7, 9, 6.5, 5, 8])

In [ ]:
# média
notas.mean()

np.float64(7.194444444444445)

In [ ]:
# desvio padrão
notas.std()

np.float64(2.4327461783453628)

In [ ]:
# mediana
notas.median()

np.float64(8.0)

DataFrame

In [ ]:
# Cria um dicionario com nomes de alunos e suas respectivas notas
dictionary = {'Alunos': ['Sandro', 'Rafael', 'Tiago', 'André', 'Camila', 'Teo', 'Carlos', 'Juca', 'Carla'],
              'Notas': [8, 10, 9.5, 7.5, 9.5, 10, 5, 6.5, 10]}

# Cria um DataFrame a partir de um dicionario
df = pd.DataFrame(data = dictionary)

# Mostra o resultado do DataFrame
df

   Alunos  Notas
0  Sandro    8.0
1  Rafael   10.0
2   Tiago    9.5
3   André    7.5
4  Camila    9.5
5     Teo   10.0
6  Carlos    5.0
7    Juca    6.5
8   Carla   10.0

In [ ]:
# 1) Nota média
df["Notas"].mean().round() # arredonde a média

np.float64(8.0)

In [ ]:
# 2) Nota do Juca
df[df["Alunos"] == "Juca"]

  Alunos  Notas
7   Juca    6.5

In [ ]:
# 3) Nota menor que 6.5
df[df["Notas"] < 6.5]

   Alunos  Notas
6  Carlos    5.0

In [ ]:
df.describe()

           Notas
count   9.000000
mean    8.444444
std     1.810463
min     5.000000
25%     7.500000
50%     9.500000
75%    10.000000
max    10.000000

In [ ]:
df[df["Notas"] > 7]['Notas'].mode()

0    10.0
Name: Notas, dtype: float64

#Trabalhando com CSV
##Dataset Titanic

In [1]:
import pandas as pd

In [2]:
titanic = pd.read_csv('titanic.csv')

In [ ]:
titanic.shape

(891, 12)

In [ ]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# unique para trazer apenas os valores únicos da coluna e serve para ver as diferente opçoes dentro da coluna

titanic['Sex'].unique()

<ArrowStringArray>
['male', 'female']
Length: 2, dtype: str

In [ ]:
#média do tícket das passagem de homens. Round para arredondar, entre aspas coloca quantas casas, se deixar em branco fica sem nenhuma casa decimal
titanic[titanic['Sex'] == 'male'] ['Fare'].mean().round(2)

np.float64(25.52)

In [ ]:
# passageiro que pagou a maior tarifa
titanic['Fare'].max()

np.float64(512.3292)

In [ ]:
# o nome do passageiro que pagou a maior tarifa
titanic[titanic['Fare'] == titanic["Fare"].max()]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: str

In [ ]:
# defina a idade média dos sobreviventes
titanic[titanic['Survived'] == 1]['Age'].mean().round()

np.float64(28.0)

In [ ]:
# Determine a classe com mais sobreviventes proporcionalmente
#  1 - quais são as classes?
titanic['Pclass'].unique()

array([3, 1, 2])

In [ ]:
total_3_classe = titanic[titanic['Pclass'] == 3].shape[0] # shape vai informar a quantidade de linhas
total_2_classe = titanic[titanic['Pclass'] == 2].shape[0]
total_1_classe = titanic[titanic['Pclass'] == 1].shape[0]

In [ ]:
#esta na 3 classe e sobreviveu
sobreviveu_3_classe = titanic[(titanic['Pclass'] == 3) & (titanic['Survived'] == 1)].shape[0]

# morreu na 3 classe
morreu_3_classe = titanic[(titanic['Pclass'] == 3) & (titanic['Survived'] == 0)].shape[0]

#proporção dos vivos 3 classe
print('vivos =', sobreviveu_3_classe/total_3_classe)

# proporção mortos 3 classe
print('mortos = ', morreu_3_classe / total_3_classe)

vivos = 0.24236252545824846
mortos =  0.7576374745417516

In [ ]:
#esta na 2 classe e sobrebiveu
sobreviveu_2_classe = titanic[(titanic['Pclass'] == 2) & (titanic['Survived'] == 1)].shape[0]

# morreu na 2 classe
morreu_2_classe = titanic[(titanic['Pclass'] == 2) & (titanic['Survived'] == 0)].shape[0]

#proporção dos vivos 2 classe
print('vivos =', sobreviveu_2_classe / total_2_classe)

# proporção mortos 2 classe
print('mortos = ', morreu_2_classe / total_2_classe)

vivos = 0.47282608695652173
mortos =  0.5271739130434783

In [ ]:
#esta na 1 classe e sobreviveu
sobreviveu_1_classe = titanic[(titanic['Pclass'] == 1) & (titanic['Survived'] == 1)].shape[0]

# morreu na 1 classe
morreu_1_classe = titanic[(titanic['Pclass'] == 1) & (titanic['Survived'] == 0)].shape[0]

#proporção dos vivos 2
# classe
print('vivos =', sobreviveu_1_classe/total_1_classe)

# proporção mortos 2
# classe
print('mortos = ', morreu_1_classe / total_1_classe)

vivos = 0.6296296296296297
mortos =  0.37037037037037035

In [4]:
# Calcula a média de Idade por Sexo
## para agruparmos usamos o metodo group by
## no parentesis passamos uma coluna ou um conjunto de colunas
## Depois precisamos passar entre colchetes o campo que vamos agrupar
## Por fim passamos a metrica que quermos

titanic.groupby('Sex')['Age'].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [5]:
# Calculo das Métricas para o Agrupamento Sexo e Idade
# Quero calcular muitas metricas na mesma linha
# podemos usar o .agg e passar uma lista de metricas

titanic.groupby(["Sex"])["Age"].agg([ "mean", "std", "count"])

             mean        std  count
Sex
female  27.915709  14.110146    261
male    30.726645  14.678201    453

In [6]:
# Com mais de uma categoria dentro do Groupby
# Quero ter mais de uma categoria
# Podemos passar no parentesis uma lista de colunas também

titanic.groupby(["Sex", "Pclass"])["Age"].agg([ "mean", "std", "count"])

                    mean        std  count
Sex    Pclass
female 1       34.611765  13.612052     85
       2       28.722973  12.872702     74
       3       21.750000  12.729964    102
male   1       41.281386  15.139570    101
       2       30.740707  14.793894     99
       3       26.507589  12.159514    253

In [7]:
# Mais de uma categoria e mais de uma métrica calculando
# Podemos calcular para um conjunto de dados diferentes as metricas
# basta passar no indexador (no colchete) uma lista de colunas
titanic.groupby(["Sex", "Pclass"])[["Age", "Survived"]].agg([ "mean", "std", "count", "sum"])

                     Age                            Survived                  \
                    mean        std count      sum      mean       std count
Sex    Pclass
female 1       34.611765  13.612052    85  2942.00  0.968085  0.176716    94
       2       28.722973  12.872702    74  2125.50  0.921053  0.271448    76
       3       21.750000  12.729964   102  2218.50  0.500000  0.501745   144
male   1       41.281386  15.139570   101  4169.42  0.368852  0.484484   122
       2       30.740707  14.793894    99  3043.33  0.157407  0.365882   108
       3       26.507589  12.159514   253  6706.42  0.135447  0.342694   347


              sum
Sex    Pclass
female 1       91
       2       70
       3       72
male   1       45
       2       17
       3       47

In [8]:
titanic.groupby('Sex')['Survived'].value_counts(normalize=True)*100
# Calcula a média de Idade por Sexo

Sex     Survived
female  1           74.203822
        0           25.796178
male    0           81.109185
        1           18.890815
Name: proportion, dtype: float64

In [9]:
titanic.groupby(['Sex', 'Pclass'])['Survived'].value_counts(normalize=True)*100

Sex     Pclass  Survived
female  1       1           96.808511
                0            3.191489
        2       1           92.105263
                0            7.894737
        3       1           50.000000
                0           50.000000
male    1       0           63.114754
                1           36.885246
        2       0           84.259259
                1           15.740741
        3       0           86.455331
                1           13.544669
Name: proportion, dtype: float64

In [ ]:
#Perguntar para o prof se posso e como renomear as colunas para o portugues - usar o rename procurar na internet
# Como converter para moeda os valores
# display aparece com aspas
# materia necessária para finalizar o trabalho
# comparativos, exemplo 3. Quem passa mais horas nas redes sociais tem um gasto maior em lojas fisicas ou online?